// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkyzzkabsbulhtozjfyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhreXp6a2Fic2J1bGh0b3pqZnl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODU5OTcsImV4cCI6MjA2ODc2MTk5N30.CviigAQy_0Y5UyIzHodz6P_FZ71crV5F1ylc8hKHeyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});